# Generated by Django 5.0.1 on 2024-02-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_hydrate_flower_alter_hydrate_time_alter_hydrate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrate',
            name='flower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.flower'),
        ),
    ]
