# Generated by Django 5.0.1 on 2024-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_hydrate_flower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrate',
            name='flower',
        ),
        migrations.AddField(
            model_name='hydrate',
            name='flower',
            field=models.ManyToManyField(to='main_app.flower'),
        ),
    ]
