# Generated by Django 5.0.1 on 2024-02-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_hydrate_flower_hydrate_flower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hydrate',
            name='flower',
        ),
        migrations.AddField(
            model_name='hydrate',
            name='flower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.flower'),
        ),
    ]
