# Generated by Django 5.0.1 on 2024-02-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_customer_alter_hydrate_options_flower_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flower',
            old_name='customer',
            new_name='customers',
        ),
    ]
