# Generated by Django 5.0.1 on 2024-02-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_customer_flower_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='customers',
            field=models.ManyToManyField(related_name='flowers', to='main_app.customer'),
        ),
    ]
